### ISSUE TITLE
Align NDA and FITBIR Datasets most recent application not working

### ISSUE THREAD

**Issue by drj143** [Nielson-Lab/NIH-database-pipeline#12]
**Describe the bug**
I tried to open the application after downloading the release from 14 days ago to my MacBook and it wouldn't load.

**To Reproduce**
1. Go to the releases 
2. Click on Align NDA and FITBIR Datasets (released 14 days ago)
3. Scroll down to MacOS_app.zip
4. See error - no error here, but when I open the zip and attempt to launch the application, it opened my browser and gave the following error (see screen capture)
<img width="784" alt="Screen Shot 2022-11-08 at 7 46 13 PM" src="https://user-images.githubusercontent.com/19963396/200716896-ddb9fb83-f9d9-4172-8ab5-f4518f16e08d.png">

**Expected behavior**
I expected the application to open in my web browser

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 
 - Browser - Chrome
 - Application Release - v0.3.0-beta-m

**Additional context**
Just trying to use the lates version of the application but it won't open.

**Comment by tk27182** [comment]
I've tried downloading and opening it on my computer (web browser: Firefox, OS: Monterey 12. 5. 1) and I get the same error. 

I compared the package contents from the downloaded app to the uploaded app and I didn't see any discrepancies. 

I wonder if it's an issue with our computers' security and opening apps from the web. Looking into that more.

**Comment by tk27182** [comment]
@drj143 If you open the Terminal, `cd` into the `MacOS_app` folder, and run the app using the command `open ./NFP.app`, does that work for you?

If that doesn't work, does the command `./NFP.app/Contents/MacOS/NFP` work?

**Comment by tk27182** [comment]
This was fixed in the pre-released version [0.3.2-beta-m](https://github.com/Nielson-Lab/NIH-database-pipeline/releases/tag/v0.3.2-beta-m). 

After checking system logs, it seems the problem was that the application tried to create the error.log file in a private folder, resulting in a permission error. This version of the application uses the [appdirs package](https://pypi.org/project/appdirs/) to save the error.log file. The application will create the new directory automatically if it does not exist.

For MacOS, the log is stored in the location /Users/your_name/Library/Logs/NFP. To make the Library folder visible if it not already, you can see this [guide](https://kb.mit.edu/confluence/display/istcontrib/How+to+make+your+Library+folder+visible+in+the+Finder+in+OS+X+10.9+%28Mavericks%29+or+later), which is still accurate for newer OS versions.
